### ISSUE TITLE
可以在特定页面中默认开启插件吗？

### ISSUE THREAD

**Issue by j1029441326** [slc3a2/dimmer#1]

**Comment by liang7hi** [comment]
暂时不支持这个功能，避免造成一些误解。 @j1029441326

**Comment by dxmaimxd** [comment]
可以在开启的时候让视频不要关灯吗?
也就是除了视频播放器其余部分关灯

**Comment by liang7hi** [comment]
抱歉，一直没注意到这个 Issue 还有更新。你说的这种情况是支持的，除了视频部分其余部分切换暗黑样式，如果有问题，麻烦提供一个网址，我会去排查一下，如果有问题不久就会发布修复版本。 @dxmaimxd

**Comment by liang7hi** [comment]
在最新的 `2.0.1` 版本的支持开启全局模式，设置 -> 开启全局模式，即可实现开启新页面后，待加载完毕，自动切换到暗黑模式 @dxmaimxd @j1029441326
