### ISSUE TITLE
深色模式只支持黑色吗

### ISSUE THREAD

**Issue by longlongvip** [slc3a2/dimmer#2]
我觉得，护眼的颜色时墨绿色

**Comment by liang7hi** [comment]
墨绿色暂时不支持，后续会考虑增加更多的自定义设置。
不过在扩展的首页，除了暗黑模式开关，下面有一些滑块，可以实现自定义调整，其中第一个亮度滤镜最后一个褐色滤镜，配合起来也可以减少对眼睛的刺激
@longlongvip

**Comment by longlongvip** [comment]
> 墨绿色暂时不支持，后续会考虑增加更多的自定义设置。 不过在扩展的首页，除了暗黑模式开关，下面有一些滑块，可以实现自定义调整，其中最后一个褐色滤镜，也可以减少对眼睛的刺激 @longlongvip

我研究一下
