### ISSUE TITLE
好多网站不支持

### ISSUE THREAD

**Issue by yitong2333** [slc3a2/dimmer#4]
比如：https://www.deepl.com/en/translator

**Comment by xbpk3t** [comment]
以及 docusaurus

**Comment by liang7hi** [comment]
https://www.deepl.com/en/translator

感谢反馈！这个网站我试了下，是可以正常切换到深色模式的，能否提供更多的信息？ @yitong2333 

<img width="1432" alt="image" src="https://github.com/user-attachments/assets/7828825d-741e-4651-b40d-bb5680a4c021">

**Comment by liang7hi** [comment]
与 #6 相同
