### ISSUE TITLE
功能反馈

### ISSUE THREAD

**Issue by yukun80** [slc3a2/dimmer#5]
作者您好，之前长期在使用另一个暗黑模式的插件（Dark Reader），使用下来发现你的插件在体积，流畅度，UI美观性确实更好，但是使用下来感觉还有可以考虑添加的功能。
我的感受如下：
1. 全局模式在修改对比度，灰度，滤镜选项后无法保存，在开启新的网页后会恢复默认；
2. 无法针对网页进行个性化，如果可以添加一个list，针对list中存在的网址采用之前设定过的设置就更好了；

希望您在有空的时候可以考虑持续更新，感谢您的开发。

**Comment by liang7hi** [comment]
@yukun80  

非常好的问题，和我的想法一样！感谢的你深度使用！

第一个问题：
- 不开启全局模式，自定义了对比度、灰度等设置，无法保存下来，刷新就恢复默认效果，这是一个 bug，下个版本将会被修复
- 全局保存自定义的，对比度、灰度等设置，针对这个问题，如果全局保存了对比度和亮度，那就可能影响所有已打开的网站，可能会有某些网站可读性造成影响，因为不同的网站的主题色，颜色搭配不同。所以我还在考虑是否如何平衡这一点：简单方便的设置，而对大部分网站不造成伤害

第二个问题
- 当修复了上面提到的 bug， 这个功能就实现了，不开启全局模式的情况下，对当前页面的所有设置都将被保存下来，下次打开这个网站应用（现 `v2.0.2` 只有暗黑模式开关会保存，其他的对比度、灰度等设置不会被保存）

再次感谢你的反馈！

**Comment by liang7hi** [comment]
在最新的 `2.0.3` 版本，修复了自定义滤镜设置无法被保存问题，并支持全局存储自定义滤镜的能力

- 开启全局`开关：所有页面都应用一份配置，这包含了自定义滤镜设置和暗黑模式开关
- 关闭全局开关：自定义滤镜和暗黑模式开关设置会被存到页面 sessionStorage 下，仅影响当前页面，并且是独立的

@yukun80

**Comment by yukun80** [comment]
您更新的速度很快，感谢！ @slc3a2
